server:
   port: 8092

spring:
   application:
      name: ventas-service
   data:
      mongodb:
         host: localhost
         port: 27017
         uri: mongodb://localhost:27017/hackathon

management:
   endpoint:
      prometheus:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'
   metrics:
      export:
         prometheus:
            enabled: true

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8091/eureka/
   instance:
      preferIpAddress: true
      hostName: 192.168.1.10