server:
   port: 8093

spring:
   application:
      name: compras-service
   data:
      mongodb:
         database: hackathon
         uri: mongodb://localhost:27017/hackathon

management:
   endpoint:
      prometheus:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'
   metrics:
      export:
         prometheus:
            enabled: true

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8091/eureka/