server:
   port: 8091

spring:
   application:
      name: eureka-service

eureka:
   instance:
      hostname: localhost
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://localhost:8091/eureka